from datetime import datetime, timezone
from app.extensions import db

class ProposalVersion(db.Model):
    """
    Model representing a generated draft version of a proposal.
    If a proposal is regenerated, a new version is created so history is kept.
    """
    __tablename__ = 'proposal_versions'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    
    # Foreign Key linking back to the parent Proposal
    proposal_id = db.Column(db.Integer, db.ForeignKey('proposals.id'), nullable=False)
    
    # Sequential version count (1, 2, 3...) for a specific proposal
    version_number = db.Column(db.Integer, nullable=False)
    
    # Tracks whether this was generated by simple rules or advanced AI
    generated_by = db.Column(
        db.Enum('RULE_ENGINE', 'AI', name='generated_by_enum'), 
        nullable=False
    )
    
    # Generated content fields
    title = db.Column(db.String(200), nullable=False)
    executive_summary = db.Column(db.Text, nullable=False)
    
    # Foreign Key pointing to the selected package in the catalogue
    proposed_package_id = db.Column(db.Integer, db.ForeignKey('gift_packages.id'), nullable=True)
    
    # Final calculated price (quantity x unit_price after discount)
    total_price = db.Column(db.Numeric(12, 2), nullable=False)
    
    closing_pitch = db.Column(db.Text, nullable=False)
    delivery_timeline = db.Column(db.Text, nullable=False)
    notes = db.Column(db.Text, nullable=True)
    
    # Timestamps
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def __repr__(self):
        return f"<ProposalVersion {self.id} (v{self.version_number}) for Proposal {self.proposal_id}>"
